export const RETRIEVE_MOVIES_GENRES_SUCCESS = "RETRIEVE_MOVIES_GENRES_SUCCESS";

export const RETRIEVE_POPULAR_MOVIES_SUCCESS =
	"RETRIEVE_POPULAR_MOVIES_SUCCESS";
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS =
	"RETRIEVE_NOWPLAYING_MOVIES_SUCCESS";
export const RETRIEVE_MOVIES_LIST_SUCCESS = "RETRIEVE_MOVIES_LIST_SUCCESS";
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = "RETRIEVE_MOVIE_DETAILS_SUCCESS";
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS =
	"RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS";

// auth actions
export const PHONE_CHANGED = "PHONE_CHANGED";
export const PHONE_CODE_CHANGED = "PHONE_CODE_CHANGED";
export const VERIFY_PHONE = "VERIFY_PHONE";
export const PHONE_VERIFICATION_CODE_SENT_SUCCESS =
	"PHONE_VERIFICATION_CODE_SENT_SUCCESS";
export const PHONE_VERIFICATION_CODE_SENT_FAIL =
	"PHONE_VERIFICATION_CODE_SENT_FAIL";
export const SET_USER = "SET_USER";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
